window.addEventListener('scroll',function(){var d=document.documentElement;var prog=document.getElementById('prog');if(prog)prog.style.width=(d.scrollTop/(d.scrollHeight-d.clientHeight)*100)+'%';});function toggleCard(card,evt){if(evt)evt.stopPropagation();var isOpen=card.classList.toggle('open');var more=card.querySelector('.more');if(more)more.style.maxHeight='';var hint=card.querySelector('.hint');if(hint){var textNode=hint.childNodes[0];if(textNode&&textNode.nodeType===3)textNode.textContent=isOpen?'CLICK TO COLLAPSE ':'CLICK TO EXPAND ';else hint.innerHTML=(isOpen?'CLICK TO COLLAPSE ':'CLICK TO EXPAND ')+'<span class="hint-arrow">▼</span>';}}
function buildDateGroups(){document.querySelectorAll('.phase-header').forEach(function(hdr){hdr.removeAttribute('onclick');if(hdr._phaseWired)return;hdr._phaseWired=true;hdr.addEventListener('click',function(e){e.stopPropagation();var block=hdr.closest?hdr.closest('.phase-block'):hdr.parentNode;if(!block)return;var isOpen=block.classList.toggle('open');hdr.setAttribute('aria-expanded',isOpen?'true':'false');var toggle=hdr.querySelector('.phase-toggle');if(toggle)toggle.textContent=isOpen?'−':'+';});});document.querySelectorAll('.date-group-header').forEach(function(hdr){if(hdr._dgWired)return;hdr._dgWired=true;hdr.classList.remove('open');var events=hdr.nextElementSibling;if(events)events.classList.remove('open');var tick=hdr.querySelector('.date-group-tick');if(tick)tick.textContent='+';hdr.addEventListener('click',function(e){e.stopPropagation();var evts=hdr.nextElementSibling;if(!evts)return;var savedY=window.scrollY||window.pageYOffset;var open=evts.classList.toggle('open');hdr.classList.toggle('open',open);if(tick)tick.textContent=open?'−':'+';var card=evts.querySelector('.card');if(open){if(card){card.classList.add('open');trackLastOpened(card);}}else{if(card)card.classList.remove('open');}
window.scrollTo(0,savedY);requestAnimationFrame(function(){window.scrollTo(0,savedY);});updateProgressTracker();});});}
function setPhaseStickyOffset(){var tabsEl=document.querySelector('.tabs');var isMobile=window.innerWidth<=480;var top=isMobile?160:155;var tabsVisible=tabsEl&&tabsEl.offsetHeight>0&&getComputedStyle(tabsEl).display!=='none';if(tabsVisible){var rect=tabsEl.getBoundingClientRect();top=Math.round(rect.bottom+(isMobile?4:12));}else{var navEl=document.getElementById('site-nav');if(navEl)top=Math.round(navEl.getBoundingClientRect().bottom+(isMobile?4:12));}
document.documentElement.style.setProperty('--phase-sticky-top',top+'px');document.documentElement.style.setProperty('--phase-sticky-top-mobile',top+'px');}
function setSimpleMode(enabled){document.body.classList.toggle('simple-mode',!!enabled);var cb=document.getElementById('ui-mode-toggle-input');if(cb)cb.checked=!!enabled;try{localStorage.setItem('llm2wmd_simple_mode',enabled?'1':'0');}catch(e){}
if(typeof window.syncTimelineTab==='function') window.syncTimelineTab();
if(typeof window.sizeHeadlinesSpacer==='function'){window.sizeHeadlinesSpacer();setTimeout(window.sizeHeadlinesSpacer,60);}
showSavePrompt(_saveProgress===null);}
function toggleSimpleMode(forceState){var enabled=typeof forceState==='boolean'?forceState:!document.body.classList.contains('simple-mode');setSimpleMode(enabled);}
function initSimpleModeToggle(){var enabled=true;try{var params=new URLSearchParams(location.search);if(params.get('simple')==='1')enabled=true;else if(params.get('simple')==='0')enabled=false;else{var saved=localStorage.getItem('llm2wmd_simple_mode');enabled=saved===null?true:saved==='1';}}catch(e){try{var saved=localStorage.getItem('llm2wmd_simple_mode');enabled=saved===null?true:saved==='1';}catch(err){enabled=true;}}setSimpleMode(enabled);}
function enhanceTimelineEntryCards(root){if(window.enhanceTimelineEntryCards&&window.enhanceTimelineEntryCards!==enhanceTimelineEntryCards)return window.enhanceTimelineEntryCards(root);}
function ensureTimelineSourceButtons(root){if(window.ensureTimelineSourceButtons&&window.ensureTimelineSourceButtons!==ensureTimelineSourceButtons)return window.ensureTimelineSourceButtons(root);}
function initPage(){buildDateGroups();if(window.enhanceTimelineEntryCards)window.enhanceTimelineEntryCards();if(window.ensureTimelineSourceButtons)window.ensureTimelineSourceButtons();buildSourcesIndex();initSimpleModeToggle();initSavePreference();setTimeout(setPhaseStickyOffset,50);setTimeout(setPhaseStickyOffset,350);var spacer=document.getElementById('mission-spacer');if(spacer){var tabsEl=document.querySelector('.tabs');var tabEl=document.querySelector('.tab');if(tabsEl&&tabEl){var tabsBottom=tabsEl.getBoundingClientRect().top+tabsEl.offsetHeight;var tabsTop=parseInt(tabsEl.style.top||window.getComputedStyle(tabsEl).top)||0;var tabsH=tabsEl.offsetHeight;spacer.style.height=(tabsTop+tabsH+32)+'px';}else{spacer.style.height='220px';}}
var rSpacer=document.getElementById('review-spacer');if(rSpacer){var tabsEl2=document.querySelector('.tabs');if(tabsEl2){var tabsTop2=parseInt(window.getComputedStyle(tabsEl2).top)||133;rSpacer.style.height=(tabsEl2.offsetHeight+tabsTop2+32)+'px';}else{rSpacer.style.height='180px';}}
var thSpacer=document.getElementById('thesis-spacer');if(thSpacer){var tabsEl3=document.querySelector('.tabs');if(tabsEl3){var tabsTop3=parseInt(window.getComputedStyle(tabsEl3).top)||133;thSpacer.style.height=(tabsEl3.offsetHeight+tabsTop3+32)+'px';}else{thSpacer.style.height='200px';}}
var ctSpacer=document.getElementById('contents-spacer');if(ctSpacer){var tabsEl4=document.querySelector('.tabs');if(tabsEl4){var tabsTop4=parseInt(window.getComputedStyle(tabsEl4).top)||133;ctSpacer.style.height=(tabsEl4.offsetHeight+tabsTop4+32)+'px';}else{ctSpacer.style.height='220px';}}
function recalcSpacers(){var tabs=document.querySelector('.tabs');if(!tabs)return;var tt=parseInt(window.getComputedStyle(tabs).top)||0;var th=tabs.offsetHeight;var h=(th+tt+32)+'px';['mission-spacer','review-spacer','thesis-spacer','contents-spacer'].forEach(function(id){var el=document.getElementById(id);if(el)el.style.height=h;});}
window.addEventListener('resize',recalcSpacers);setTimeout(recalcSpacers,300);function applyTabLabels(){var mobile=window.innerWidth<=480;document.querySelectorAll('.tab[data-full]').forEach(function(t){t.textContent=mobile?t.dataset.mobile:t.dataset.full;});}
applyTabLabels();window.addEventListener('resize',function(){applyTabLabels();setTimeout(setPhaseStickyOffset,50);});(function(){var fragments=['SCANNING ARGUMENT STRUCTURE...','CROSS-REFERENCING TIMELINE DATA...','CALCULATING WORD COUNT...','ASSESSING RHETORICAL IMPACT...','THREAT LEVEL: SIGNIFICANT','CHECKING FOR NEUTRALITY: NONE FOUND','BIAS DETECTED: INTENTIONAL','SOURCES: DOCUMENTED','FOOTNOTES: PENDING','DRAFT STATUS: DRAFT 0.0','AUTHOR LOCATION: UNKNOWN','DEADLINE: SELF-IMPOSED','SELF-IMPOSED DEADLINE: IGNORED','IRONY LEVELS: ELEVATED','ESTIMATED PAGES: MANY','ESTIMATED PAGES: TOO MANY','ARGUMENT: IN PROGRESS','CONCLUSION: REACHED. WRITTEN? NO.','WORD COUNT: INSUFFICIENT','WORD COUNT: EXCESSIVE','REDRAFTING...','STILL REDRAFTING...','OPENING LINE: DELETED AGAIN',];var stream=document.getElementById('thesis-stream');var bar=document.getElementById('thesis-bar');var label=document.getElementById('thesis-progress-label');var wc=document.getElementById('thesis-wordcount');var fakeWords=0;var fakeProgress=0;if(!stream)return;var wcTick=setInterval(function(){fakeWords+=Math.floor(Math.random()*40+10);if(fakeWords>847){fakeWords=847;clearInterval(wcTick);if(wc)wc.textContent=fakeWords+' WORDS · INCOMPLETE';}
else if(wc)wc.textContent=fakeWords+' WORDS';},120);setTimeout(function(){if(bar)bar.style.width='12%';if(label)label.textContent='12% · STALLED';},1800);var si=0;var streamTick=setInterval(function(){if(!document.getElementById('thesis-stream')){clearInterval(streamTick);return;}
var line=document.createElement('div');line.textContent='> '+fragments[si%fragments.length];stream.appendChild(line);if(stream.children.length>4)stream.removeChild(stream.firstChild);si++;},1400);})();window.addEventListener('resize',function(){var spacer=document.getElementById('mission-spacer');var tabsEl=document.querySelector('.tabs');if(spacer&&tabsEl){var tabsTop=tabsEl.offsetTop||133;spacer.style.height=(tabsEl.offsetHeight+parseInt(window.getComputedStyle(tabsEl).top)+32)+'px';}
setPhaseStickyOffset();});var evs=document.querySelectorAll('.ev');for(var i=0;i<evs.length;i++)evs[i].classList.add('vis');var tabMappings=[['tab-timeline','timeline'],['tab-mission','mission'],['tab-credits','credits'],['tab-thesis','thesis'],['tab-review','review'],['tab-contents','contents']];tabMappings.forEach(function(pair){var el=document.getElementById(pair[0]);if(!el)return;el.addEventListener('touchstart',function(e){switchTab(pair[1],el);},{passive:true});});var defPage=document.getElementById('page-mission');if(defPage){defPage.style.display='block';defPage.classList.add('active');}
setTimeout(function(){window.scrollTo(0,1);window.scrollTo(0,0);},50);}
var _lastOpenedTitle='';var _lastOpenedEl=null;var _saveProgress=null;function lsGet(k){try{return localStorage.getItem(k);}catch(e){return null;}}
function lsSet(k,v){try{localStorage.setItem(k,v);}catch(e){}}
function lsDel(k){try{localStorage.removeItem(k);}catch(e){}}
function initSavePreference(){var saved=lsGet('llm2wmd_save_progress');if(saved==='1'){_saveProgress=true;showSaveStatus(true);restoreProgressFromStorage();}else if(saved==='0'){_saveProgress=false;showSaveStatus(false);}else{_saveProgress=null;showSavePrompt(true);}}
function showSavePrompt(visible){var el=document.getElementById('rail-save-prompt');if(el)el.style.display=visible?'':'none';}
function showSaveStatus(saving){var el=document.getElementById('rail-save-status');if(!el)return;if(saving){el.style.display='';el.childNodes[0].textContent='PROGRESS SAVED \u00a0\u00b7\u00a0 ';}else{el.style.display='none';}}
function setSavePreference(save){_saveProgress=save;lsSet('llm2wmd_save_progress',save?'1':'0');showSavePrompt(false);showSaveStatus(save);if(!save){lsDel('llm2wmd_last_title');lsDel('llm2wmd_opened_titles');}else{persistProgress();}}
function promptSavePreference(forceShow){showSavePrompt(true);}
function persistProgress(){if(!_saveProgress)return;if(_lastOpenedTitle)lsSet('llm2wmd_last_title',_lastOpenedTitle);var openCards=document.querySelectorAll('#page-timeline .card.open');var titles=[];openCards.forEach(function(c){var et=c.querySelector('.et');if(et)titles.push(et.textContent.trim());});lsSet('llm2wmd_opened_titles',JSON.stringify(titles));}
function restoreProgressFromStorage(){var lastTitle=lsGet('llm2wmd_last_title');if(lastTitle){_lastOpenedTitle=lastTitle;var lastTitleEl=document.getElementById('rail-last-title');var resumeBtn=document.getElementById('rail-resume-btn');if(lastTitleEl)lastTitleEl.textContent=lastTitle.length>42?lastTitle.slice(0,40)+'\u2026':lastTitle;if(resumeBtn)resumeBtn.style.display='';document.querySelectorAll('#page-timeline .card').forEach(function(c){var et=c.querySelector('.et');if(et&&et.textContent.trim()===lastTitle)_lastOpenedEl=c;});}
var raw=lsGet('llm2wmd_opened_titles');if(!raw)return;var titles=[];try{titles=JSON.parse(raw);}catch(e){return;}
if(!titles.length)return;var titleSet={};titles.forEach(function(t){titleSet[t]=true;});document.querySelectorAll('#page-timeline .card').forEach(function(c){var et=c.querySelector('.et');if(!et||!titleSet[et.textContent.trim()])return;c.classList.add('open');var dg=c.closest('.date-group');if(dg){var hdr=dg.querySelector('.date-group-header');var evts=dg.querySelector('.date-group-events');if(hdr)hdr.classList.add('open');if(evts)evts.classList.add('open');var tick=dg.querySelector('.date-group-tick');if(tick)tick.textContent='\u2212';}
var phase=c.closest('.phase-block');if(phase){phase.classList.add('open');var toggle=phase.querySelector('.phase-toggle');if(toggle)toggle.textContent='\u2212';}});updateProgressTracker();}
function updateProgressTracker(){var total=document.querySelectorAll('#page-timeline .card').length;if(!total)return;var opened=document.querySelectorAll('#page-timeline .card.open').length;var pct=total?Math.round((opened/total)*100):0;var titleEl=document.getElementById('rail-progress-title');var barEl=document.getElementById('rail-progress-bar');var pctEl=document.getElementById('rail-progress-pct');if(titleEl)titleEl.textContent=opened+' of '+total+' opened';if(barEl)barEl.style.width=pct+'%';if(pctEl)pctEl.textContent=pct+'% COMPLETE';persistProgress();}
function trackLastOpened(cardEl){var titleEl=cardEl.querySelector('.et');if(!titleEl)return;_lastOpenedTitle=titleEl.textContent.trim();_lastOpenedEl=cardEl;var lastTitle=document.getElementById('rail-last-title');var resumeBtn=document.getElementById('rail-resume-btn');if(lastTitle)lastTitle.textContent=_lastOpenedTitle.length>42?_lastOpenedTitle.slice(0,40)+'\u2026':_lastOpenedTitle;if(resumeBtn)resumeBtn.style.display='';persistProgress();}
function resumeLastEntry(){if(!_lastOpenedEl)return;switchTab('timeline',document.getElementById('tab-timeline'));setTimeout(function(){var phase=_lastOpenedEl.closest('.phase-block');if(phase&&!phase.classList.contains('open')){phase.classList.add('open');var toggle=phase.querySelector('.phase-toggle');if(toggle)toggle.textContent='−';}
var dg=_lastOpenedEl.closest('.date-group');if(dg){var hdr=dg.querySelector('.date-group-header');var evts=dg.querySelector('.date-group-events');if(hdr)hdr.classList.add('open');if(evts)evts.classList.add('open');var tick=dg.querySelector('.date-group-tick');if(tick)tick.textContent='−';}
if(!_lastOpenedEl.classList.contains('open')){_lastOpenedEl.classList.add('open');updateProgressTracker();}
setTimeout(function(){_lastOpenedEl.scrollIntoView({behavior:'smooth',block:'center'});},80);},180);}
function expandAllPhases(){document.querySelectorAll('.phase-block').forEach(function(b){b.classList.add('open');var toggle=b.querySelector('.phase-toggle');if(toggle)toggle.textContent='−';});document.querySelectorAll('.date-group-header').forEach(function(hdr){hdr.classList.add('open');var evts=hdr.nextElementSibling;if(evts){evts.classList.add('open');var card=evts.querySelector('.card');if(card)card.classList.add('open');}
var tick=hdr.querySelector('.date-group-tick');if(tick)tick.textContent='−';});updateProgressTracker();}
function collapseAllPhases(){document.querySelectorAll('.phase-block').forEach(function(b){b.classList.remove('open');var toggle=b.querySelector('.phase-toggle');if(toggle)toggle.textContent='+';});document.querySelectorAll('.date-group-header').forEach(function(hdr){hdr.classList.remove('open');var evts=hdr.nextElementSibling;if(evts)evts.classList.remove('open');var tick=hdr.querySelector('.date-group-tick');if(tick)tick.textContent='+';});document.querySelectorAll('#page-timeline .card').forEach(function(c){c.classList.remove('open');});updateProgressTracker();}
var _origToggleCard=toggleCard;toggleCard=function(card,evt){_origToggleCard(card,evt);if(card.classList.contains('open'))trackLastOpened(card);updateProgressTracker();};function filt(t,btn){document.querySelectorAll('.hero-filters .fb').forEach(function(b){b.classList.remove('on');});if(btn)btn.classList.add('on');document.querySelectorAll('.co-filters .fb').forEach(function(b){b.classList.remove('on');});document.querySelectorAll('.ev').forEach(function(ev){ev.classList.remove('gone');});var groups=document.querySelectorAll('.date-group');groups.forEach(function(group){var groupEvs=group.querySelectorAll('.ev');var anyVisible=false;groupEvs.forEach(function(ev){var matches=t==='all'||ev.getAttribute('data-t')===t;ev.classList.toggle('gone',!matches);if(matches)anyVisible=true;});group.style.display=anyVisible?'':'none';});}
function filtCo(co,btn){document.querySelectorAll('.co-filters .fb').forEach(function(b){b.classList.remove('on');});if(btn)btn.classList.add('on');document.querySelectorAll('.hero-filters .fb').forEach(function(b){b.classList.remove('on');});document.querySelectorAll('.ev').forEach(function(ev){ev.classList.remove('gone');});var groups=document.querySelectorAll('.date-group');groups.forEach(function(group){var groupEvs=group.querySelectorAll('.ev');var anyVisible=false;groupEvs.forEach(function(ev){var matches=ev.getAttribute('data-co')===co;ev.classList.toggle('gone',!matches);if(matches)anyVisible=true;});group.style.display=anyVisible?'':'none';});}
window.__openTodayGameInternal=null;window.LLM2WMDApp=window.LLM2WMDApp||(function(){var state={currentPage:'mission'};var tabs=['tab-timeline','tab-mission','tab-credits','tab-contact','tab-thesis','tab-review','tab-contents','tab-faq','tab-sources'];var RESUME_KEY='llm2wmd_last_place_v1';function readResume(){try{var data=JSON.parse(localStorage.getItem(RESUME_KEY)||'{}');return data&&typeof data==='object'?data:{};}catch(e){return {};}}function writeResume(data){try{localStorage.setItem(RESUME_KEY,JSON.stringify(data||{}));}catch(e){}}function saveCurrentPlace(){var data=readResume();data.page=state.currentPage||'mission';data.scroll=Math.max(0,window.scrollY||window.pageYOffset||0);writeResume(data);}function restorePlaceForPage(id){var data=readResume();if(data.page!==id)return;var y=Math.max(0,Number(data.scroll||0));setTimeout(function(){window.scrollTo(0,y);},0);}function getOverlay(){return document.getElementById('today-game-overlay');}
function closeMountedGame(){if(typeof window.closeTodayGame==='function')return window.closeTodayGame();return false;}
function applyPageSideEffects(id){window.scrollTo(0,0);if(id==='timeline'){document.querySelectorAll('.ev').forEach(function(ev){ev.classList.add('vis');});document.querySelectorAll('.phase-header').forEach(function(hdr){if(hdr._phaseWired)return;hdr._phaseWired=true;hdr.addEventListener('click',function(e){e.stopPropagation();var block=hdr.closest?hdr.closest('.phase-block'):hdr.parentNode;if(!block)return;var isOpen=block.classList.toggle('open');var toggle=hdr.querySelector('.phase-toggle');if(toggle)toggle.textContent=isOpen?'−':'+';});});document.querySelectorAll('.card.ce .more').forEach(function(more){var card=more.closest('.card');var eb=more.querySelector('.eb');var layout=more.querySelector('.timeline-summary-layout');if(card&&eb&&layout&&layout.contains(eb))card.insertBefore(eb,more);var det=more.querySelector('.det');var fullWrap=more.querySelector('.timeline-full-entry-wrap');if(fullWrap&&det&&fullWrap.contains(det))more.insertBefore(det,more.firstChild);more.querySelectorAll('.timeline-summary-layout,.timeline-source-btn-wrap,.timeline-full-entry-wrap').forEach(function(el){el.remove();});if(det)det.style.display='';});if(window.enhanceTimelineEntryCards)window.enhanceTimelineEntryCards();if(window.ensureTimelineSourceButtons)window.ensureTimelineSourceButtons();updateProgressTracker();}
if(id==='sources')buildSourcesIndex();if(typeof maybeShowTabIntro==='function')maybeShowTabIntro(id);}
function switchPage(id,opts){opts=opts||{};saveCurrentPlace();var ov=getOverlay();if(ov&&ov.style.display==='flex')closeMountedGame();document.querySelectorAll('.page').forEach(function(p){p.style.display='none';p.classList.remove('active');});tabs.forEach(function(tid){var t=document.getElementById(tid);if(t)t.classList.remove('active');});var page=document.getElementById('page-'+id);if(page){page.style.display='block';page.classList.add('active');state.currentPage=id;}
var activeTab=document.getElementById('tab-'+id);if(activeTab)activeTab.classList.add('active');if(!opts.fromPop){try{var current=(history.state&&history.state.page)?history.state.page:null;if(current!==id)history.pushState({page:id},'','#'+id);}catch(e){}}
applyPageSideEffects(id);if(opts.restoreSavedPlace)restorePlaceForPage(id);else window.scrollTo(0,0);saveCurrentPlace();return true;}
function initHistory(){window.addEventListener('popstate',function(e){var page=(e.state&&e.state.page)?e.state.page:'mission';switchPage(page,{fromPop:true});});window.addEventListener('scroll',saveCurrentPlace,{passive:true});window.addEventListener('beforeunload',saveCurrentPlace);document.addEventListener('DOMContentLoaded',function(){try{var initial='mission';var resume=readResume();var wantsShop=false;var wantsVip=false;if(location.hash){var hashPage=location.hash.replace('#','');if(hashPage==='shop'||hashPage==='shop-section'){wantsShop=true;if(resume.page&&document.getElementById('page-'+resume.page))initial=resume.page;}else if(hashPage==='vip'||hashPage==='vip-signup'||hashPage==='survivor-signup-section'){wantsShop=true;wantsVip=true;if(resume.page&&document.getElementById('page-'+resume.page))initial=resume.page;}else if(document.getElementById('page-'+hashPage))initial=hashPage;}else if(resume.page&&document.getElementById('page-'+resume.page)){initial=resume.page;}
history.replaceState({page:initial},'','#'+(wantsVip?'vip':(wantsShop?'shop':initial)));window.LLM2WMDApp.router.switchPage(initial,{fromPop:true,restoreSavedPlace:!wantsShop&&!location.hash&&resume.page===initial});if(wantsVip){if(typeof window.llm2wmdGoToVip==='function')window.llm2wmdGoToVip();}else if(wantsShop){setTimeout(function(){var shopEl=document.getElementById('shop-section');if(shopEl){shopEl.scrollIntoView({behavior:'auto',block:'start'});history.replaceState({page:initial},'','#shop');}},60);}}catch(e){window.LLM2WMDApp.router.switchPage('mission',{fromPop:true});}});}
return{state:state,router:{switchPage:switchPage,initHistory:initHistory},game:{open:function(){if(typeof window.__openTodayGameInternal==='function')return window.__openTodayGameInternal();return false;},close:closeMountedGame},certs:{show:function(certData){window.__llm2wmd_pendingCert=certData;if(typeof showCertPanel==='function')showCertPanel(certData);}}};})();window.openTodayGame=function(){return window.LLM2WMDApp.game.open();};window.launchGame=function(){return window.LLM2WMDApp.game.open();};if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initPage);}else{initPage();}
function switchTab(id,el,opts){return window.LLM2WMDApp.router.switchPage(id,opts);}
window.LLM2WMDApp.router.initHistory();function showChooseLife(){var el=document.getElementById('choose-life-overlay');if(el){el.style.display='block';window.scrollTo(0,0);}}
function closeGame(){return window.LLM2WMDApp.game.close();}